/**
 * Export utilities for caregiver reports
 * Generates PDF and CSV exports of patient data
 */

export interface ReportData {
  patientName: string
  patientId: string
  dateRange: { start: Date; end: Date }
  summary: {
    totalAlerts: number
    wanderingEvents: number
    agitationEvents: number
    medicationCompliance: number
    mealCompliance: number
    averageAgitation: number
  }
  alerts: Array<{
    id: string
    type: string
    message: string
    urgency: string
    timestamp: Date
    status: string
  }>
  patterns: Array<{
    type: string
    confidence: number
    description: string
    recommendation: string
  }>
  dailyStats: Array<{
    date: string
    alerts: number
    avgAgitation: number
    interventions: number
    wanderingEvents: number
  }>
}

// Generate CSV content
export function generateCSV(data: ReportData): string {
  const headers = [
    'Date',
    'Alert Type',
    'Message',
    'Urgency',
    'Status',
    'Agitation Level',
    'Interventions',
    'Wandering Events'
  ]

  const rows: string[][] = []

  // Add summary row
  rows.push([
    'SUMMARY',
    '',
    `Report for ${data.patientName}`,
    '',
    '',
    data.summary.averageAgitation.toFixed(2),
    data.summary.totalAlerts.toString(),
    data.summary.wanderingEvents.toString()
  ])

  rows.push([]) // Empty row for spacing

  // Add alerts
  data.alerts.forEach(alert => {
    rows.push([
      new Date(alert.timestamp).toLocaleDateString(),
      alert.type,
      `"${alert.message.replace(/"/g, '""')}"`,
      alert.urgency,
      alert.status,
      '',
      '',
      ''
    ])
  })

  // Add daily stats
  rows.push([]) // Empty row
  rows.push(['DAILY STATISTICS'])
  rows.push(['Date', 'Alerts', 'Avg Agitation', 'Interventions', 'Wandering Events'])
  
  data.dailyStats.forEach(stat => {
    rows.push([
      stat.date,
      stat.alerts.toString(),
      stat.avgAgitation.toFixed(2),
      stat.interventions.toString(),
      stat.wanderingEvents.toString()
    ])
  })

  // Combine into CSV string
  const csvContent = [
    headers.join(','),
    ...rows.map(row => row.join(','))
  ].join('\n')

  return csvContent
}

// Generate a simple text-based report (fallback when PDF generation isn't available)
export function generateTextReport(data: ReportData): string {
  const lines: string[] = []

  lines.push('═'.repeat(60))
  lines.push('AEGIS CAREGIVER - PATIENT CARE REPORT')
  lines.push('═'.repeat(60))
  lines.push('')
  lines.push(`Patient: ${data.patientName}`)
  lines.push(`Patient ID: ${data.patientId}`)
  lines.push(`Report Period: ${data.dateRange.start.toLocaleDateString()} - ${data.dateRange.end.toLocaleDateString()}`)
  lines.push('')
  lines.push('─'.repeat(60))
  lines.push('SUMMARY')
  lines.push('─'.repeat(60))
  lines.push(`Total Alerts: ${data.summary.totalAlerts}`)
  lines.push(`Wandering Events: ${data.summary.wanderingEvents}`)
  lines.push(`Agitation Events: ${data.summary.agitationEvents}`)
  lines.push(`Medication Compliance: ${(data.summary.medicationCompliance * 100).toFixed(1)}%`)
  lines.push(`Meal Compliance: ${(data.summary.mealCompliance * 100).toFixed(1)}%`)
  lines.push(`Average Agitation Level: ${(data.summary.averageAgitation * 100).toFixed(1)}%`)
  lines.push('')

  lines.push('─'.repeat(60))
  lines.push('DETECTED PATTERNS')
  lines.push('─'.repeat(60))
  data.patterns.forEach(pattern => {
    lines.push(`• ${pattern.type} (${(pattern.confidence * 100).toFixed(0)}% confidence)`)
    lines.push(`  ${pattern.description}`)
    lines.push(`  Recommendation: ${pattern.recommendation}`)
    lines.push('')
  })

  lines.push('─'.repeat(60))
  lines.push('RECENT ALERTS')
  lines.push('─'.repeat(60))
  data.alerts.slice(0, 10).forEach(alert => {
    lines.push(`[${new Date(alert.timestamp).toLocaleString()}] ${alert.urgency.toUpperCase()}: ${alert.type}`)
    lines.push(`  ${alert.message}`)
    lines.push(`  Status: ${alert.status}`)
    lines.push('')
  })

  lines.push('═'.repeat(60))
  lines.push('Generated by Aegis Caregiver')
  lines.push('Powered by Gemini Live API')
  lines.push('═'.repeat(60))

  return lines.join('\n')
}

// Download file utility
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// Export report as CSV
export function exportCSV(data: ReportData) {
  const csv = generateCSV(data)
  const filename = `aegis-report-${data.patientName.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.csv`
  downloadFile(csv, filename, 'text/csv')
}

// Export report as text (can be saved as .txt)
export function exportTextReport(data: ReportData) {
  const text = generateTextReport(data)
  const filename = `aegis-report-${data.patientName.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`
  downloadFile(text, filename, 'text/plain')
}

// Generate demo report data
export function generateDemoReportData(patientName: string, patientId: string): ReportData {
  const endDate = new Date()
  const startDate = new Date(endDate)
  startDate.setDate(startDate.getDate() - 7)

  const dailyStats = []
  for (let i = 6; i >= 0; i--) {
    const date = new Date(endDate)
    date.setDate(date.getDate() - i)
    dailyStats.push({
      date: date.toISOString().split('T')[0],
      alerts: Math.floor(Math.random() * 5),
      avgAgitation: 0.2 + Math.random() * 0.3,
      interventions: Math.floor(Math.random() * 3),
      wanderingEvents: Math.floor(Math.random() * 2)
    })
  }

  return {
    patientName,
    patientId,
    dateRange: { start: startDate, end: endDate },
    summary: {
      totalAlerts: 23,
      wanderingEvents: 5,
      agitationEvents: 8,
      medicationCompliance: 0.92,
      mealCompliance: 0.85,
      averageAgitation: 0.28
    },
    alerts: [
      { id: '1', type: 'wandering', message: 'Patient approached exit', urgency: 'high', timestamp: new Date(Date.now() - 3600000), status: 'resolved' },
      { id: '2', type: 'agitation', message: 'Elevated agitation detected (65%)', urgency: 'normal', timestamp: new Date(Date.now() - 7200000), status: 'resolved' },
      { id: '3', type: 'health', message: 'Meal reminder: 6 hours since last meal', urgency: 'normal', timestamp: new Date(Date.now() - 10800000), status: 'acknowledged' },
      { id: '4', type: 'medication', message: 'Medication reminder triggered', urgency: 'low', timestamp: new Date(Date.now() - 14400000), status: 'resolved' },
    ],
    patterns: [
      { type: 'sundowning', confidence: 0.85, description: 'Elevated agitation 4-7 PM', recommendation: 'Start calming activities at 3:30 PM' },
      { type: 'wandering_risk', confidence: 0.78, description: 'Wandering after 30+ min silence', recommendation: 'Increase proactive engagement' },
      { type: 'medication_timing', confidence: 0.92, description: 'Best compliance 8:00-8:30 AM', recommendation: 'Schedule prompts at 8:00 AM' },
    ],
    dailyStats
  }
}
